# Generated by Django 3.0.5 on 2021-03-19 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название объекта')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_number', models.CharField(max_length=100, unique=True, verbose_name='Уникальный номер сенсора')),
                ('building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objects', to='sensors.Building', verbose_name='Объект')),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Показание')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата показания')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='sensors.Sensor', verbose_name='Сенсор')),
            ],
        ),
    ]
