# Generated by Django 3.0.5 on 2021-03-19 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название датчика')),
            ],
        ),
        migrations.CreateModel(
            name='SensorValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sens_uid', models.IntegerField(unique=True, verbose_name='Уникальный идентификатор датчика')),
                ('value', models.BigIntegerField(verbose_name='Показание')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата показания')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.Building')),
            ],
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='building',
        ),
        migrations.DeleteModel(
            name='Value',
        ),
        migrations.AddField(
            model_name='sensorvalues',
            name='pin_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.Sensor'),
        ),
        migrations.AddField(
            model_name='sensorvalues',
            name='sens',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.Sens'),
        ),
    ]
