# Generated by Django 3.1.7 on 2021-03-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='object',
            new_name='building',
        ),
        migrations.AlterField(
            model_name='building',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название объекта'),
        ),
        migrations.AlterField(
            model_name='value',
            name='value',
            field=models.IntegerField(verbose_name='Показание'),
        ),
    ]
