# Generated by Django 3.0.5 on 2021-03-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_auto_20210319_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorvalues',
            name='sens_uid',
            field=models.IntegerField(verbose_name='Уникальный идентификатор датчика'),
        ),
    ]
