# Generated by Django 3.1.7 on 2021-03-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_auto_20210318_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='value',
            field=models.FloatField(verbose_name='Показание'),
        ),
    ]
