# Generated by Django 3.1.7 on 2021-05-03 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='поле для рисунка', null=True, upload_to='sensors/buildings_plans/', verbose_name='Изображение')),
                ('img_coordinates', models.JSONField(verbose_name='Координаты для плана')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название объекта')),
                ('adress', models.CharField(max_length=200, unique=True, verbose_name='Адрес объекта')),
                ('coordinates_lat', models.FloatField(default=1, verbose_name='Долгота')),
                ('coordinates_lon', models.FloatField(default=1, verbose_name='Широта')),
                ('phone_number', models.CharField(default='+79214462524', max_length=12, verbose_name='Номер телефона инженера по эксплуатации')),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
        migrations.CreateModel(
            name='LeakSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sens_uid', models.CharField(max_length=100, unique=True, verbose_name='Уникальный номер системы протечки')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaksensor', to='sensors.building', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Система мониторинга протечек',
                'verbose_name_plural': 'Системы мониторинга протечек',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sens_uid', models.CharField(max_length=100, unique=True, verbose_name='Уникальный номер датчика снега')),
                ('max_value', models.PositiveIntegerField(default=200, verbose_name='Значение для отправки уведомлений, кг/м2')),
                ('response_comand', models.CharField(default='ok', max_length=100, verbose_name='Команда для ответа с сервера')),
                ('response_update_time', models.PositiveIntegerField(default='60', verbose_name='Период обновления показателей, сек')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='sensors.building', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Датчик снега',
                'verbose_name_plural': 'Датчики снега',
            },
        ),
        migrations.CreateModel(
            name='TemperatureSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sens_uid', models.CharField(max_length=100, unique=True, verbose_name='Уникальный номер датчика температуры')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperaturesensor', to='sensors.building', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Датчик температуры',
                'verbose_name_plural': 'Датчики температуры',
            },
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(verbose_name='Температура')),
                ('snow', models.FloatField(verbose_name='Снег')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата показания')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.building', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Погодные данные',
                'verbose_name_plural': 'Погодные данные',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='TemperatureSensorValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Показание датчика температуры')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата показания')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperaturesensorvalues', to='sensors.temperaturesensor', verbose_name='Датчик температуры')),
            ],
            options={
                'verbose_name': 'Показания датчика температуры',
                'verbose_name_plural': 'Показания датчиков температуры',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='SensorValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Показание датчика снега')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата показания')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensorvalues', to='sensors.sensor', verbose_name='Датчик снега')),
            ],
            options={
                'verbose_name': 'Показания датчиков снега',
                'verbose_name_plural': 'Показания датчиков снега',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='LeakSensorValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=10000, verbose_name='Показание системы мониторинга протечек')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата показания')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaksensorvalues', to='sensors.leaksensor', verbose_name='Система мониторинга протечек')),
            ],
            options={
                'verbose_name': 'Показание системы мониторинга протечек',
                'verbose_name_plural': 'Показания системы мониторинга протечек',
                'ordering': ('-pub_date',),
            },
        ),
    ]
