# Generated by Django 3.1.7 on 2021-03-23 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name': 'Объект', 'verbose_name_plural': 'Объекты'},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'verbose_name': 'Датчик', 'verbose_name_plural': 'Датчики'},
        ),
        migrations.AlterModelOptions(
            name='sensorvalues',
            options={'verbose_name': 'Показания датчиков', 'verbose_name_plural': 'Показания датчиков'},
        ),
    ]
