# Generated by Django 3.1.7 on 2021-03-26 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_auto_20210323_0525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensorvalues',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Показания датчиков', 'verbose_name_plural': 'Показания датчиков'},
        ),
    ]
