# Generated by Django 3.1.7 on 2021-03-30 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_auto_20210326_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='coordinates_lat',
            field=models.FloatField(default=1, verbose_name='Долгота'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='coordinates_lon',
            field=models.FloatField(default='1', verbose_name='Широта'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(verbose_name='Температура')),
                ('snow', models.FloatField(verbose_name='Снег')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата показания')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.building', verbose_name='Объект')),
                ('sensors', models.ManyToManyField(to='sensors.Sensor')),
            ],
            options={
                'verbose_name': 'Погодные данные',
                'verbose_name_plural': 'Погодные данные',
                'ordering': ('-pub_date',),
            },
        ),
    ]
