# Generated by Django 3.1.7 on 2021-03-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_auto_20210330_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='coordinates_lat',
            field=models.FloatField(default=1, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='building',
            name='coordinates_lon',
            field=models.FloatField(default=1, verbose_name='Широта'),
        ),
    ]
