# Generated by Django 3.1.7 on 2021-03-30 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_auto_20210330_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='sensors',
        ),
    ]
