# Generated by Django 3.1.7 on 2021-04-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0006_remove_weather_sensors'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='max_value',
            field=models.PositiveIntegerField(default=200, verbose_name='Значение для отправки уведомлений'),
        ),
    ]
