# Generated by Django 3.1.7 on 2021-04-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0007_sensor_max_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='phone_number',
            field=models.CharField(default='+79214462524', max_length=12, verbose_name='Номер телефона инженера по эксплуатации'),
        ),
    ]
