# Generated by Django 3.1.7 on 2021-04-06 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sensors', '0008_building_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='auth.user', verbose_name='Заказчик'),
            preserve_default=False,
        ),
    ]
