# Generated by Django 3.1.7 on 2021-04-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0010_auto_20210406_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='response_comand',
            field=models.CharField(default=0, max_length=100, verbose_name='Команда для ответа с сервера'),
        ),
    ]
