# Generated by Django 3.1.7 on 2021-04-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0012_auto_20210407_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='response_comand',
            field=models.CharField(choices=[('reboot', 'REBOOT'), ('tare', 'TARE'), ('ok', 'OK')], default='ok', max_length=100, verbose_name='Команда для ответа с сервера'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sens_uid',
            field=models.CharField(max_length=100, unique=True, verbose_name='Уникальный номер датчика'),
        ),
    ]
