# Generated by Django 3.1.7 on 2021-04-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0013_auto_20210407_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='response_comand',
            field=models.CharField(max_length=100, verbose_name='Команда для ответа с сервера'),
        ),
    ]
