# Generated by Django 3.1.7 on 2021-04-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0014_auto_20210407_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='response_comand',
            field=models.CharField(default='ok', max_length=100, verbose_name='Команда для ответа с сервера'),
        ),
    ]
