# Generated by Django 3.1.7 on 2021-04-10 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0015_auto_20210408_0558'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sens_uid', models.CharField(max_length=100, unique=True, verbose_name='Уникальный номер датчика')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.building', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Датчик температуры',
                'verbose_name_plural': 'Датчики температуры',
            },
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'verbose_name': 'Датчик снега', 'verbose_name_plural': 'Датчики снега'},
        ),
        migrations.CreateModel(
            name='TemperatureSensorValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Показание')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата показания')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.temperaturesensor', verbose_name='Датчик')),
            ],
            options={
                'verbose_name': 'Показания датчиков',
                'verbose_name_plural': 'Показания датчиков',
                'ordering': ('-pub_date',),
            },
        ),
    ]
