# Generated by Django 3.1.7 on 2021-04-11 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0016_auto_20210410_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensorvalues',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Показания датчиков снега', 'verbose_name_plural': 'Показания датчиков снега'},
        ),
        migrations.AlterModelOptions(
            name='temperaturesensorvalues',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Показания датчика температуры', 'verbose_name_plural': 'Показания датчиков температуры'},
        ),
        migrations.AddField(
            model_name='sensor',
            name='response_update_time',
            field=models.PositiveIntegerField(default='60', verbose_name='Период обновления показателей'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sens_uid',
            field=models.CharField(max_length=100, unique=True, verbose_name='Уникальный номер датчика снега'),
        ),
        migrations.AlterField(
            model_name='sensorvalues',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.sensor', verbose_name='Датчик снега'),
        ),
        migrations.AlterField(
            model_name='sensorvalues',
            name='value',
            field=models.FloatField(verbose_name='Показание датчика снега'),
        ),
        migrations.AlterField(
            model_name='temperaturesensor',
            name='sens_uid',
            field=models.CharField(max_length=100, unique=True, verbose_name='Уникальный номер датчика температуры'),
        ),
        migrations.AlterField(
            model_name='temperaturesensorvalues',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.temperaturesensor', verbose_name='Датчик температуры'),
        ),
        migrations.AlterField(
            model_name='temperaturesensorvalues',
            name='value',
            field=models.FloatField(verbose_name='Показание датчика температуры'),
        ),
    ]
