# Generated by Django 3.1.7 on 2021-04-12 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0017_auto_20210411_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='sensors.building', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='max_value',
            field=models.PositiveIntegerField(default=200, verbose_name='Значение для отправки уведомлений, кг/м2'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='response_update_time',
            field=models.PositiveIntegerField(default='60', verbose_name='Период обновления показателей, сек'),
        ),
    ]
