# Generated by Django 3.1.7 on 2021-04-12 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0019_auto_20210412_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorvalues',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensorvalues', to='sensors.sensor', verbose_name='Датчик снега'),
        ),
        migrations.AlterField(
            model_name='temperaturesensorvalues',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperaturesensorvalues', to='sensors.temperaturesensor', verbose_name='Датчик температуры'),
        ),
    ]
