# Generated by Django 3.1.7 on 2021-04-12 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0020_auto_20210412_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturesensor',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperaturesensor', to='sensors.building', verbose_name='Объект'),
        ),
    ]
