# Generated by Django 3.1.7 on 2021-04-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0022_building_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='image',
            field=models.ImageField(help_text='поле для рисунка', null=True, upload_to='static/buildings_plans/', verbose_name='Изображение'),
        ),
    ]
