# Generated by Django 3.1.7 on 2021-04-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0024_auto_20210429_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='image',
            field=models.ImageField(help_text='поле для рисунка', null=True, upload_to='sensors/buildings_plans/', verbose_name='Изображение'),
        ),
    ]
