# Generated by Django 3.1.7 on 2021-04-29 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0025_auto_20210429_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeakSensorValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=10000, verbose_name='Показание системы мониторинга протечек')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата показания')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaksensorvalues', to='sensors.temperaturesensor', verbose_name='Система мониторинга протечек')),
            ],
            options={
                'verbose_name': 'Показание системы мониторинга протечек',
                'verbose_name_plural': 'Показания системы мониторинга протечек',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='LeakSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sens_uid', models.CharField(max_length=100, unique=True, verbose_name='Уникальный номер системы протечки')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaksensor', to='sensors.building', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Система мониторинга протечек',
                'verbose_name_plural': 'Системы мониторинга протечек',
            },
        ),
    ]
