# Generated by Django 3.1.7 on 2021-04-29 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0026_leaksensor_leaksensorvalues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaksensorvalues',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaksensorvalues', to='sensors.leaksensor', verbose_name='Система мониторинга протечек'),
        ),
    ]
