# Generated by Django 3.1.7 on 2021-05-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0027_auto_20210429_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='img_coordinates',
            field=models.CharField(max_length=400, null=True, verbose_name='Координаты плана'),
        ),
    ]
