# Generated by Django 3.1.7 on 2021-05-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0028_building_img_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='img_coordinates',
            field=models.CharField(max_length=2000, null=True, verbose_name='Координаты плана'),
        ),
    ]
