# Generated by Django 3.1.7 on 2021-05-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0031_auto_20210501_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='img_coordinates',
            field=models.JSONField(null=True),
        ),
    ]
