# Generated by Django 3.1.7 on 2021-05-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0032_auto_20210501_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='img_coordinates',
            field=models.CharField(max_length=500, null=True, verbose_name='Координаты для плана'),
        ),
    ]
