# Generated by Django 3.1.7 on 2021-05-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0034_auto_20210501_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='img_coordinates',
            field=models.JSONField(verbose_name='Координаты для плана'),
        ),
    ]
